name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  hacs:
    runs-on: ubuntu-latest
    name: HACS
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v4"

      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"